spring:
  config:
    activate:
      on-profile: local
    import: "optional:configserver:" # Config Server 없어도 에러 무시
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      database: 391

  cloud:
    config:
      enabled: false          # Config Client 기능 끄기

    gateway:
      discovery:
        locator:
          enabled: true       # Eureka 서비스 자동 발견 활성화
      routes:
        # [추가] 로그아웃은 인증이 필요하므로 필터를 적용해야 함! (순서 중요: 위쪽에 배치)
        - id: user-service-logout
          uri: lb://TEAM5-MEMBER-SERVER
          predicates:
            - Path=/api/auth/logout
            - Method=POST
          filters:
            - AuthorizationHeaderFilter

        - id: user-service-public
          # 중요: Member Service의 application.name과 대소문자/스펠링이 일치해야 함
          # 아래 Member 설정에서 이름을 'member-service'로 통일하는 것을 권장
          uri: lb://TEAM5-MEMBER-SERVER
          predicates:
            - Path=/api/auth/**

        - id: user-service-secure
          uri: lb://TEAM5-MEMBER-SERVER
          predicates:
            - Path=/api/members/admin/**
          filters:
            - name: AuthorizationHeaderFilter
              args:
                role: ADMIN

        - id: user-service-secure
          uri: lb://TEAM5-MEMBER-SERVER
          predicates:
            - Path=/api/members/**
          filters:
            - AuthorizationHeaderFilter

        - id: user-service-address
          uri: lb://TEAM5-MEMBER-SERVER
          predicates:
            - Path=/api/address/**
          filters:
            - AuthorizationHeaderFilter

        - id: user-service-cart
          uri: lb://TEAM5-MEMBER-SERVER
          predicates:
            - Path=/api/cart/**
          filters:
            - AuthorizationHeaderFilter

        - id: coupon-service
          uri: lb://TEAM5-COUPON-SERVER
          predicates:
            - Path=/api/coupons/**

        - id: book-service
          uri: lb://TEAM5-BOOK-SERVER
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix= 2

        - id: payment-service
          uri: lb://TEAM5-PAYMENT-SERVER
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix= 2

        - id: order-service
          uri: lb://TEAM5-ORDER-SERVER
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix= 2
eureka:
  client:
    enabled: true             # Eureka Client 켜기 (중요!)
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/


jwt:
  secret: "v3RyS3cr3tK3yF0rJwT5ign1ngPurp0s3sOnlyD0N0tSh4r3Th1s"
  expiration_time: 50000
  refresh_expiration_time: 100000

server:
  port: 8082