server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://TEAM5-MEMBER-SERVER
          predicates:
            - Path=/api/cart/**, /api/points/**, /api/admin/points/**, /internal/**

        - id: coupon-service
          uri: lb://TEAM5-COUPON-SERVER
          predicates:
            - Path=/api/coupons/**

        - id: book-service
          uri: lb://TEAM5-BOOK-SERVER
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix= 2

        - id: payment-service
          uri: lb://TEAM5-PAYMENT-SERVER
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix= 2

        - id: order-service
          uri: lb://TEAM5-ORDER-SERVER
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix= 2


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/